version: '3.4'
services:
  tests:
    image: golang:1.15
    container_name: tests
    volumes:
      - "../../:/go/src/app"
    working_dir: /go/src/app
    command: go test -v -race -failfast -p 1 -covermode=atomic -coverprofile=coverage.out ./...

networks:
  default:
    external:
      name: ${NETWORK}
